CREATE TABLE t_family (
f_id INT NOT NULL AUTO_INCREMENT,
f_url VARCHAR(255) NOT NULL,
f_name VARCHAR(100),
f_time TIMESTAMP NOT NULL default now(),
PRIMARY KEY (f_id)
);

CREATE TABLE t_person (
p_id INT NOT NULL AUTO_INCREMENT,
p_url VARCHAR(255) NOT NULL,
p_name VARCHAR(100),
p_gender VARCHAR(30),
f_id INT NOT NULL,
PRIMARY KEY (p_id),
CONSTRAINT fk_person FOREIGN KEY (f_id) REFERENCES t_family(f_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE t_small_face (
s_id INT NOT NULL AUTO_INCREMENT,
s_url VARCHAR(255) NOT NULL,
f_id INT NOT NULL,
PRIMARY KEY (s_id),
CONSTRAINT fk_small_face FOREIGN KEY (f_id) REFERENCES t_family(f_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE t_kinship (
k_id INT NOT NULL AUTO_INCREMENT,
p_id_1 INT NOT NULL,
p_id_2 INT NOT NULL,
k_relationship INT NOT NULL,
PRIMARY KEY (k_id),
CONSTRAINT fk_p_1 FOREIGN KEY (p_id_1) REFERENCES t_person(p_id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_p_2 FOREIGN KEY (p_id_2) REFERENCES t_person(f_id) ON DELETE CASCADE ON UPDATE CASCADE
);