/*
 * Filename:      ml_test_data.h
 * Copyright:     2013, Zhicong Chen
 * Version:       
 * Author:        Zhicong Chen <zhicong.chen@changecong.com>
 * Created at:    Fri Nov  8 12:20:50 2013
 * Modified at:   Wed Nov 13 11:54:28 2013
 * Modified by:   Zhicong Chen <zhicong.chen@changecong.com>
 * Status:        Experimental, do not distribute.
 * Description:   This is a class used to generate test data.
 *                Our test data would be generated by two images. 
 *                The test data is the difference between two images
 *
 */

#ifndef KINVRF_ML_TEST_DATA_H
#define KINVRF_ML_TEST_DATA_H

#include "ml_data.h"  // class Data
#include <cstring>

using namespace std;

namespace kinvrf_ml {

    ///\class
    ///\brief

    class TestData : public Data {

      public:

        ///\fn
        ///\brief
        TestData(const string& path_one, const string& path_two);

        ///\fn
        ///\brief
        Mat test_data_one();
        
        ///\fn
        ///\brief
        Mat test_data_two();

      private:

        ///\fn
        ///\brief
        TestData();

        ///\fn
        ///\brief
        void init();

        ///\fn
        ///\brief
        void get_data();

        string image_one_;  ///< path of the first image
        string image_two_;  ///< path of the second image

        Mat test_data_one_;
        Mat test_data_two_;

    };  // class TestData 

}  // namespace kinvrf_ml

#endif  // KINVRF_ML_TEST_DATA_H
