/*
 * Filename:      ml_test_data.h
 * Copyright:     2013, Zhicong Chen
 * Version:       
 * Author:        Zhicong Chen <zhicong.chen@changecong.com>
 * Created at:    Fri Nov  8 12:20:50 2013
 * Modified at:   Sat Nov 16 23:04:58 2013
 * Modified by:   Zhicong Chen <zhicong.chen@changecong.com>
 * Status:        Experimental, do not distribute.
 * Description:   This is a class used to generate test data.
 *                Our test data would be generated by two images. 
 *                The test data is the difference between two images
 *
 */

#ifndef KINVRF_ML_TEST_DATA_H
#define KINVRF_ML_TEST_DATA_H

#include "ml_data.h"  // class Data
#include <cstring>

using namespace std;

///\namespace kinvrf_ml
///\brief Contains functions and classes which are defined for Machine Learning module of the project.
namespace kinvrf_ml {

    ///\class TestData
    ///\brief A derived class of class Data. Used to contain the test data.
    class TestData : public Data {

      public:

        ///\fn TestData(const string& path_one, const string& path_two)
        ///\param [in] path_one The path of first image.
        ///\param [in] path_two The path of second image.
        ///\brief The test data is generated by the diff of two images. By default 
        ///       assume the image one is the image of younger person, image two is 
        ///       the elder.
        TestData(const string& path_one, const string& path_two);

        ///\fn Mat test_data_one()
        ///\return A cv::Mat object.
        ///\brief Return the diff of the first image minus the second image.
        Mat test_data_one();
        
        ///\fn Mat test_data_two()
        ///\return A cv::Mat object.
        ///\brief Return the diff of the second image minus the first image.
        Mat test_data_two();

      private:

        ///\fn TestData()
        ///\brief The dafault constructor which is declared as private.
        TestData();

        ///\fn
        ///\brief
        void init();

        ///\fn
        ///\brief
        void get_data();

        string image_one_;  ///< path of the first image
        string image_two_;  ///< path of the second image

        Mat test_data_one_;
        Mat test_data_two_;

    };  // class TestData 

}  // namespace kinvrf_ml

#endif  // KINVRF_ML_TEST_DATA_H
