/*
 * Filename:      ml_test_data.h
 * Copyright:     2013, Zhicong Chen
 * Version:       
 * Author:        Zhicong Chen <zhicong.chen@changecong.com>
 * Created at:    Fri Nov  8 12:20:50 2013
 * Modified at:   Fri Nov  8 12:49:48 2013
 * Modified by:   Zhicong Chen <zhicong.chen@changecong.com>
 * Status:        Experimental, do not distribute.
 * Description:   This is a class used to generate test data.
 *                Our test data would be generated by two images. 
 *                The test data is the difference between two images
 *
 */

#ifndef KINVRF_ML_TEST_DATA_H
#define KINVRF_ML_TEST_DATA_H

#include "ml_data.h"  // class Data
#include <cstring>

using namespace std;

namespace kinvrf_ml {

    ///\class
    ///\brief

    class TestData : virtual public Data {

      public:
        
        ///\fn
        ///\brief
        vitual TestData();

        ///\fn
        ///\brief
        explicit TestData(const string& path_one, const string& path_two);

      private:

        string image_one_;  ///< path of the first image
        string image_two_;  ///< path of the second image

    };  // class TestData 

}  // namespace kinvrf_ml

#endl  // KINVRF_ML_TEST_DATA_H
